# This file belongs in ~/.config/starship.toml

command_timeout = 1000

[character]
success_symbol = "âš¡ï¸"

[java]
format = "via [â˜•ï¸ $version](bold red) "

[nodejs]
format = "via [ğŸ¤– $version](bold green) "

